name = "MyStorefront Postback"
client_id = "ab5565dc8f31ff5263247c38e852ac31"
application_url = "https://hashtopic-postback-shopify.onrender.com"
embedded = true

[access_scopes]
scopes = "read_customers,read_orders,write_orders,read_products,read_themes,write_themes,read_script_tags,write_script_tags,read_price_rules,write_price_rules,read_discounts"

[auth]
redirect_urls = [
  "https://hashtopic-postback-shopify.onrender.com/api/auth/callback"
]

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = ["orders/paid", "orders/updated"]
  uri = "/api/webhooks"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "fashionbrandhouse.myshopify.com"
