name = "HashTopic Postback"
client_id = "cabe3de7ab3c6bf8f95c6b7aa2d88b25"
application_url = "https://hashtopic-postback-shopify.onrender.com"
embedded = true

[access_scopes]
scopes = "read_orders,read_customers"

[auth]
redirect_urls = [
  "https://hashtopic-postback-shopify.onrender.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

  [[webhooks.subscriptions]]
  topics = ["orders/paid", "orders/updated"]
  uri = "/api/webhooks"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "YOUR_DEV_STORE.myshopify.com"
